name: {{cookiecutter.project_name}}
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.21
  - pandas>=1.3
  - matplotlib>=3.4
  - scikit-learn>=0.24
  - pip
  - jupyter
  - seaborn
